In [1]:
import numpy as np


def init_p():  # 初始化前驱矩阵
    p = np.full((n, n), None)
    for i in range(n):
        for j in range(n):
            if j != i and not np.isinf(w[i, j]):
                p[i, j] = i + 1
    return p


def sp_all_dp():
    l = np.array(w, copy=True)
    p = init_p()  # 初始化前驱矩阵
    for _ in range(n):
        for i in range(n):
            for j in range(n):
                for k in range(n):
                    if l[i, k] + w[k, j] < l[i, j]:
                        l[i, j] = l[i, k] + w[k, j]  # 更新L
                        p[i, j] = k + 1  # 更新前驱
    return l, p


def sp_all_dp_plus():
    l = np.array(w, copy=True)
    p = init_p()  # 初始化前驱矩阵
    m = 1
    while m < 2 * n:
        for i in range(n):
            for j in range(n):
                for k in range(n):
                    if l[i, k] + l[k, j] < l[i, j]:
                        l[i, j] = l[i, k] + l[k, j]  # 更新L
                        p[i, j] = p[k, j]  # 更新前驱
        m *= 2
    return l, p


def floyd_warshall():
    d = np.array(w, copy=True)
    p = init_p()  # 初始化前驱矩阵
    for k in range(n):
        for i in range(n):
            for j in range(n):
                if d[i, k] + d[k, j] < d[i, j]:
                    d[i, j] = d[i, k] + d[k, j]  # 更新d
                    p[i, j] = p[k, j]  # 更新前驱
    return d, p


# 邻接矩阵
I = float("inf")
w = np.array(
    [
        [0, 3, 8, I, -4],
        [I, 0, I, 1, 7],
        [I, 4, 0, I, I],
        [2, I, -5, 0, I],
        [I, I, I, 6, 0],
    ]
)
n = len(w)

print(sp_all_dp())
print(sp_all_dp_plus())
print(floyd_warshall())

(array([[ 0.,  1., -3.,  2., -4.],
       [ 3.,  0., -4.,  1., -1.],
       [ 7.,  4.,  0.,  5.,  3.],
       [ 2., -1., -5.,  0., -2.],
       [ 8.,  5.,  1.,  6.,  0.]]), array([[None, 3, 4, 5, 1],
       [4, None, 4, 2, 1],
       [4, 3, None, 2, 1],
       [4, 3, 4, None, 1],
       [4, 3, 4, 5, None]], dtype=object))
(array([[ 0.,  1., -3.,  2., -4.],
       [ 3.,  0., -4.,  1., -1.],
       [ 7.,  4.,  0.,  5.,  3.],
       [ 2., -1., -5.,  0., -2.],
       [ 8.,  5.,  1.,  6.,  0.]]), array([[None, 3, 4, 5, 1],
       [4, None, 4, 2, 1],
       [4, 3, None, 2, 1],
       [4, 3, 4, None, 1],
       [4, 3, 4, 5, None]], dtype=object))
(array([[ 0.,  1., -3.,  2., -4.],
       [ 3.,  0., -4.,  1., -1.],
       [ 7.,  4.,  0.,  5.,  3.],
       [ 2., -1., -5.,  0., -2.],
       [ 8.,  5.,  1.,  6.,  0.]]), array([[None, 3, 4, 5, 1],
       [4, None, 4, 2, 1],
       [4, 3, None, 2, 1],
       [4, 3, 4, None, 1],
       [4, 3, 4, 5, None]], dtype=object))
