In [ ]:
import numpy as np

a = np.arange(16).reshape(4,4)
print(a)

b = slice(1,3)
c = slice(2, None)
d = b,c
print(a[d])
print(a[d].shape)

int(3<2)

index = np.argmin([3,3,4])
print(index)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 6  7]
 [10 11]]
(2, 2)
1
